config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots, only: [:index, :show, :new, :create] do
    resources :videos, only: [:new, :create]
    resources :reviews, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :update] do
    member do
      get :profile
    end
  end

  namespace :dashboard do
    resources :videos, only: [:index]
  end

  resources :videos, only: [:update] do
    resources :comments, only: [:create]
  end

  get '/videos/:id/upvote', to: 'videos#upvote', as: 'upvote'
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :check_ins, class_name: "User", foreign_key: "spot_id"
  has_many :favorites, dependent: :destroy
  has_many :reviews
  has_many :videos
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode, if: :will_save_change_to_latitude?

  CATEGORIES = ["spot", "shop"]
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :name, uniqueness: true
  validates :description, length: { within: 10..140 }
end

app/controllers/spots_controller.rb
require 'exifr/jpeg'

class SpotsController < ApplicationController
  before_action :authenticate_user!, except: [ :home, :index, :show ]

  def index
    @spots = policy_scope(Spot)
    if params[:spot].present? && params[:query].present?
      sql_query = " \
      (spots.name @@ :query \
      OR spots.description @@ :query \
      OR spots.address @@ :query \)
      AND spots.category @@ :spot \
      "
      @spots = Spot.where(sql_query, query: "%#{params[:query]}%", spot: "%#{params[:spot]}%")
      if @spots.empty?
        @spots = policy_scope(Spot)
      end

    elsif params[:spot].present?
      sql_query = " \
      spots.category @@ :spot \
      "
      @spots = Spot.where(sql_query, spot: "%#{params[:spot]}%")


  elsif params[:shop].present? && params[:query].present?
      sql_query = " \
      (spots.name @@ :query \
      OR spots.description @@ :query \
      OR spots.address @@ :query \)
      AND spots.category @@ :shop \
      "

      @spots = Spot.where(sql_query, shop: "%#{params[:shop]}%", query: "%#{params[:query]}%")
      if @spots.empty?
        @spots = policy_scope(Spot)
      end

    elsif params[:shop].present?
      sql_query = " \
      spots.category @@ :shop \
      "
      @spots = Spot.where(sql_query, shop: "%#{params[:shop]}%")

    elsif params[:query].present?
      sql_query = " \
      spots.name @@ :query \
      OR spots.description @@ :query \
      OR spots.category @@ :query \
      OR spots.address @@ :query \
      "
      @spots = Spot.where(sql_query, query: "%#{params[:query]}%")
    else
      @spots = policy_scope(Spot)
    end

    @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { spot: spot })
      }
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @top_video = @spot.videos.sort_by(&:votes).last
    @videos = @spot.videos.where.not(id: @top_video).order(created_at: :desc)
    authorize @spot
    @reviews = @spot.reviews
    @review = Review.new
    @video = Video.new
    @comment = Comment.new
  end

  def new
    @spot = Spot.new
    authorize @spot
  end

  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user
    authorize @spot
    if @spot.address.blank?
     gps_latitude = MiniMagick::Image.open(spot_params[:photos][0].tempfile.path).exif["GPSLatitude"]
     result = gps_latitude.split(',')
      latitude_sum = (result[0].split("/")[0].to_i) + ((result[1].split("/")[0].to_i)/60.0) +  (((result[2].split("/")[0].to_i)/(result[2].split("/")[1]).to_f)/3600.0)
      @spot.latitude = latitude_sum
       result = gps_latitude.split(',')
      latitude_sum = (result[0].split("/")[0].to_i) + ((result[1].split("/")[0].to_i)/60.0) +  (((result[2].split("/")[0].to_i)/(result[2].split("/")[1]).to_f)/3600.0)
      @spot.latitude = latitude_sum
      gps_longitude = MiniMagick::Image.open(spot_params[:photos][0].tempfile.path).exif["GPSLongitude"]
      result = gps_longitude.split(',')
      longitude_sum = (result[0].split("/")[0].to_i) + ((result[1].split("/")[0].to_i)/60.0) +  (((result[2].split("/")[0].to_i)/(result[2].split("/")[1]).to_f)/3600.0)
      @spot.longitude = longitude_sum
      @spot.address = @spot.reverse_geocode
      respond_to do |format|
        format.html
        format.js
      end
      @spot.address = @spot.reverse_geocode
    else
      if @spot.save
        redirect_to @spot, notice: 'Spot added!'
      else
        redirect_to @spot, notice: 'Spot added!'
      end
    end
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :address, :category, :description, photos:[])
  end
end

app/views/spots/_checked_in.html.erb
<div id="checked_in">
  <% if spot.check_ins.length > 0 %>
    <div class="d-flex justify-content-center mt-3">
      <h2>Skaters at this spot now...</h2>
    </div>
    <% spot.check_ins.order(updated_at: :asc).each do |user| %>
      <% if user_signed_in? && user == current_user %>
        <%= link_to dashboard_videos_path do %>
          <%= cl_image_tag user.photo.attached? ? cl_image_path(user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered overlaid" %>
        <% end %>
      <% else %>
        <%= link_to user_path(user.id) do %>
          <%= cl_image_tag user.photo.attached? ? cl_image_path(user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered overlaid" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/spots/_form.html.erb
<%= simple_form_for @spot, remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="add-a-spot">
    <div class="back-button">
      <%= link_to spots_path do %>
        <i class="fas fa-arrow-circle-left"></i>
      <% end %>
    </div>
    <h1 class="text-center">Add a Spot</h1>
    <div id="spot-input">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :category, as: :radio_buttons, collection: ['spot', 'shop'] %>
    </div>
    <div id="spot-btn-upload">
      <%= f.input :photos, as: :file, input_html: { multiple: true, onChange: "Rails.fire(this.form, 'submit')" } %>
    </div>
      <%= f.input :address %>
    <div id="spot-btn-create">
      <%= f.button :submit, 'Add spot'%>
    </div>
  </div>
<% end %>

app/views/spots/_info_window.html.erb
<div class="carousel-container">
  <div data-controller="carousel" class="swiper-container" id="show" data-carousel-options-value='{
    "pagination": { "el": ".swiper-pagination",
                    "dynamicBullets": "true" },
    "navigation": { "nextEl": ".swiper-button-next",
                    "prevEl": ".swiper-button-prev"}}'>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-pagination" id="pagination-index"></div>
    <div class="swiper-wrapper">
      <% spot.photos.each do |photo| %>
        <div class="swiper-slide">
          <div class="spot-preview">
            <%=link_to cl_image_tag(photo.key, style: 'height: 30vh; width: 95vw;'), spot %>
            <div class="ml-4">
              <h5 class="spot-info">
                <%= link_to spot.name.capitalize, spot %>
                <div id="rating">
                  <% sum = 0 %>
                  <% counter = spot.reviews.size %>
                  <% spot.reviews.each do |review| %>
                    <% sum += review.rating %>
                  <% end %>
                  <p class="small">Avg Rating: <%= spot.reviews.empty? ? "None yet" : sum/counter %></p>
                </div>
              </h5>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/_review-modal.html.erb
<% if @spot.category == "shop" %>
  <div class="container mb-3">
    <% if current_user.present? %>
      <div class="btn-upload mb-3">
        <%= render 'reviews/modal' %>
      </div>
    <% else %>
      <div class="btn-upload mb-3">
        <%= link_to "Review", new_user_session_path, class: "btn btn-gradient" %>
      <% end %>
    </div>
    <% if @spot.reviews.empty? %>
      <div class='container mt-5 text-center'>
        <p>No reviews yet.</p>
        <p>Be the first to leave a review for <%= @spot.name %>!</p>
      </div>
    <% else %>
      <% @spot.reviews.each do |review| %>
        <p><em><%= review.comment %></em></p>
        <div class="d-flex">
          <% review.rating.times do %>
            <p><em><i class="fas fa-star"></i> </em></p>
          <% end %>
        </div>
      <% end %>
      <hr>
    <% end %>
  </div>
<% end %>

app/views/spots/_review_carousel.html.erb
<% if @spot.reviews.empty? %>
  <div class='container mt-5 text-center'>
    <p>No reviews yet.</p>
    <p>Be the first to leave a review for <%= @spot.name %>!</p>
  </div>
<% else %>
  <div data-controller="carousel" class="swiper-container" id="show">
    <div class="swiper-wrapper">
      <% @spot.reviews.each do |review| %>
        <div class="swiper-slide">
          <p><em><%= review.comment %></em></p>
          <div class="d-flex">
            <% review.rating.times do %>
              <p><em><i class="fas fa-star"></i> </em></p>
            <% end %>
          </div>
        </div>
      <% end %>
      <hr>
    </div>
  </div>
<% end %>

app/views/spots/_spot-category-shop.html.erb
<div class="container my-3">
  <% if current_user.present? %>
    <div class="btn-upload my-3">
      <%= render 'reviews/modal' %>
    </div>
  <% else %>
    <div class="btn-upload my-3">
      <%= link_to "Review", new_user_session_path, class: "btn btn-gradient" %>
    <% end %>
  </div>
  <% if @spot.reviews.empty? %>
    <div class='container mt-5 text-center'>
      <p>No reviews yet.</p>
      <p>Be first to leave a review for <%= @spot.name %>!</p>
    </div>
  <% else %>
    <div class="container ml-a">
      <% @spot.reviews.each do |review| %>
        <p><em><i class="fas fa-quote-left"></i> <%= review.comment %></em></p>
        <div class="d-flex">
          <% review.rating.times do %>
            <p class="small p-1"><em><i class="fas fa-star"></i> </em></p>
          <% end %>
        </div>
        <hr class="mt-3">
      <% end %>
    </div>
  <% end %>
</div>

app/views/spots/_spot-category-spot.html.erb
<div class="flex mt-3 overlay" id="spot-div">
  <%= render 'checked_in', spot: @spot %>
</div>
<ul class="nav tabs-underlined" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="active tab-underlined" id="home-tab" data-toggle="tab" href="#my-socks" role="tab" aria-controls="home" aria-selected="true">Videos</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="tab-underlined" id="profile-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="profile" aria-selected="false">Reviews</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade py-3 show active" id="my-socks" role="tabpanel" aria-labelledby="home-tab">
    <div class="container my-3">
      <div class="btn-upload my-3">
        <% if current_user.present? %>
          <%= render 'videos/modal' %>
        <% else %>
          <%= link_to "Upload Video", new_user_session_path, class: "btn btn-gradient" %>
        <% end %>
      </div>
      <% if @spot.videos.empty? %>
        <p class="text-center">No videos. Be the first to add one!</p>
      <% else %>
        <h2 class="ml-5 mt-3">Top Video</h2>
        <div class="card-video">
          <%= render 'top_video', spot: @spot, top_video: @top_video %>
        </div>
        <div>
          <h2 class="ml-5 mt-5">Videos</h2>
          <%= render 'videos', spot: @spot, videos: @videos %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade py-3 my-3" id="bookings" role="tabpanel" aria-labelledby="profile-tab">
    <div class="container my-3">
      <div class="btn-upload my-3">
        <% if current_user.present? %>
          <%= render 'reviews/modal' %>
        <% else %>
          <%= link_to "Review", new_user_session_path, class: "btn btn-gradient" %>
        <% end %>
      </div>
      <% if @spot.reviews.empty? %>
        <div class='container mt-5 text-center'>
          <p>No reviews yet.</p>
          <p>Be the first to leave a review for <%= @spot.name %>!</p>
        </div>
      <% else %>
        <div class="container ml-4">
          <% @spot.reviews.each do |review| %>
            <p><em><i class="fas fa-quote-left"></i> <%= review.comment %></em></p>
            <div class="d-flex">
              <% review.rating.times do %>
                <p class="small"><em><i class="fas fa-star"></i> </em></p>
              <% end %>
            </div>
            <hr class="mt-3">
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/_spot-details.html.erb
<div class="spot">
  <div class="show-head">
    <h1 id="spot-name" data-lat="<%= @spot.latitude %>" data-long="<%= @spot.longitude %>"><%= @spot.name %></h1>
    <p></i><%= @spot.description %></p>
  <p><i class="fas fa-map-marker-alt" id="marker"></i> <%= @spot.address %></p>
  <div class="carousel-container">
    <% if current_user %>
      <div class='star-btn' id="favorite_button">
        <%= render "favorites/favorite", spot: @spot %>
      </div>
    <% end %>
    <div data-controller="carousel" class="swiper-container" id="show" data-carousel-options-value='{
    "pagination": { "el": ".swiper-pagination",
                    "dynamicBullets": "true" },
    "navigation": { "nextEl": ".swiper-button-next",
                    "prevEl": ".swiper-button-prev"}}'>
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
      <div class="swiper-pagination"></div>
      <div class="swiper-wrapper">
        <% if @spot.photos.attached? %>
          <% @spot.photos.each do |photo| %>
            <div class="swiper-slide">
              <%= cl_image_tag(photo.key)%>
            </div>
          <% end %>
        <% else %>
          <% @spot.photos.each do |photo| %>
            <div class="swiper-slide">
              <%= image_tag(photo)%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spots/_top_video.html.erb
<%= cl_video_tag(top_video.video.key, controls: true, width: 300, class: "card-img-top") %>
<% if user_signed_in? && top_video.user == current_user %>
  <%= link_to dashboard_videos_path do  %>
    <%= cl_image_tag top_video.user.photo.attached? ? cl_image_path(top_video.user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered" %>
  <% end %>
<% else %>
  <%= link_to user_path(top_video.user.id) do  %>
    <%= cl_image_tag top_video.user.photo.attached? ? cl_image_path(top_video.user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered" %>
  <% end %>
<% end %>
<div class="video-infos" id="video-<%= top_video.id %>">
  <div>
    <p><i class="fas fa-quote-left"></i> <%= top_video.caption %></p>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <p class="mr-5" id="counter-video-<%= top_video.id %>"><%= top_video.votes %></p>
    <% if current_user.nil? %>
      <%= link_to new_user_session_path do %>
        <p><i class="fas fa-thumbs-up"></i></p>
      <% end %>
    <% else %>
      <%= link_to upvote_path(top_video), remote: true do %>
        <% if current_user.voted_up_on?(top_video) %>
          <p ><i class="fas fa-thumbs-up mystyle" id="thumbs-video-<%= top_video.id %>"></i></p>
        <% else %>
          <p><i class="fas fa-thumbs-up" id="thumbs-video-<%= top_video.id %>"></i></p>
        <% end %>
      <% end %>
    <% end %>
    <p><i data-video-id="<%= top_video.id %>" class="fas fa-comments comment-list"></i></p>
  </div>
</div>
<div class="comments" id="comments-<%= top_video.id %>" >
  <%= render 'comments/modal', video: top_video %>
  <% top_video.comments.each do |comment| %>
    <i class="fas fa-quote-left"></i><p><em><%= comment.comment %></em></p>
  <% end %>
</div>

app/views/spots/_videos.html.erb
<% videos.each do |video| %>
  <div class="card-video mb-5">
    <%= cl_video_tag(video.video.key, controls: true, width: 300, class: "card-img-top") %>
    <div>
      <% if user_signed_in? && video.user == current_user %>
        <%= link_to dashboard_videos_path do  %>
          <%= cl_image_tag video.user.photo.attached? ? cl_image_path(video.user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered" %>
        <% end %>
      <% else %>
        <%= link_to user_path(video.user.id) do  %>
          <%= cl_image_tag video.user.photo.attached? ? cl_image_path(video.user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered" %>
        <% end %>
      <% end %>
    </div>
    <div class="video-infos" id="video-<%= video.id %>">
      <div>
        <p><i class="fas fa-quote-left"></i> <%= video.caption.capitalize %></p>
      </div>
      <div class="d-flex align-items-center justify-content-center">
        <p class="mr-5" id="counter-video-<%= video.id %>"><%= video.votes %></p>
        <% if current_user.nil? %>
          <%= link_to new_user_session_path do %>
            <p><i class="fas fa-thumbs-up"></i></p>
          <% end %>
        <% else %>
          <%= link_to upvote_path(video), remote: true do %>
            <% if current_user.voted_up_on?(video) %>
              <p ><i class="fas fa-thumbs-up" style="color: #ed9090"></i></p>
            <% else %>
              <p><i class="fas fa-thumbs-up"></i></p>
            <% end %>
          <% end %>
        <% end %>
        <p><i data-video-id="<%= video.id %>" class="fas fa-comments comment-list"></i></p>
      </div>
    </div>
    <div class="comments" id="comments-<%= video.id %>" >
      <%= render 'comments/modal', video: video %>
      <% video.comments.each do |comment| %>
        <i class="fas fa-quote-left"></i><p><em><%= comment.comment %></em></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/spots/create.js.erb
document.querySelector('#spot_address').value = "<%= @spot.address %>"

app/views/spots/index.html.erb
<%= render 'shared/search' %>
<div id="map"
  style="width: 100%; height: 79vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/spots/new.html.erb
<div class="container">
  <%= render 'form', spot: @spot %>
</div>

app/views/spots/show.html.erb
<%= render 'shared/search' %>
<%= render 'spot-details' %>
<% if @spot.category == "spot" %>
  <%= render 'spot-category-spot' %>
<% else %>
  <%= render 'spot-category-shop' %>
<% end %>
<% if current_user && current_user.spot_id != @spot.id %>
  <div style="display: none">
    <%= simple_form_for current_user, html: {id:"check-in-form"}, remote: true do |f| %>
      <%= f.input :spot_id, input_html: {value: @spot.id} %>
      <%= f.button :submit %>
    <% end %>
  </div>
<% end %>