config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots, only: [:index, :show, :new, :create] do
    resources :videos, only: [:new, :create]
    resources :reviews, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :update] do
    member do
      get :profile
    end
  end

  namespace :dashboard do
    resources :videos, only: [:index]
  end

  resources :videos, only: [:update] do
    resources :comments, only: [:create]
  end

  get '/videos/:id/upvote', to: 'videos#upvote', as: 'upvote'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @spot = Spot.find(params[:spot_id])
    @favorite = Favorite.create(user_id: current_user.id, spot_id: @spot.id)
    authorize @favorite
  end

  def destroy
    @spot = Spot.find(params[:spot_id])
    @favorite = Favorite.find_by(user_id: current_user.id, spot_id: @spot.id)
    authorize @favorite
    @favorite.destroy
  end
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, spot_id: spot.id) %>
  <%= link_to spot_favorites_path(spot.id), method: :post, remote: true, class:"like-btn" do %>
    <i class="far fa-heart star-icon1"></i>
  <% end %>
<% else %>
  <%= link_to spot_favorite_path(spot_id: spot.id, id: spot.favorites[0].id), method: :delete, remote: true, class:"like-btn" do %>
    <i class="fas fa-heart star-icon2"></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
document.querySelector("#favorite_button").innerHTML = "<%= j render partial: "favorites/favorite", locals: {spot: @favorite.spot} %>"

app/views/favorites/destroy.js.erb
document.querySelector("#favorite_button").innerHTML = "<%= j render partial: "favorites/favorite", locals: {spot: @favorite.spot} %>"