config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots, only: [:index, :show, :new, :create] do
    resources :videos, only: [:new, :create]
    resources :reviews, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :update] do
    member do
      get :profile
    end
  end

  namespace :dashboard do
    resources :videos, only: [:index]
  end

  resources :videos, only: [:update] do
    resources :comments, only: [:create]
  end

  get '/videos/:id/upvote', to: 'videos#upvote', as: 'upvote'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :spot, optional: true
  has_many :videos
  has_many :spots
  has_many :favorites
  has_one_attached :photo
  has_many :videos_as_owner, through: :spots, source: :videos

  validates :username, presence: true
  validates :username, uniqueness: true

  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: :update
  def show
    @user = User.find(params[:id])
    authorize @user
    @comment = Comment.new
    if current_user
      favorites = Favorite.where(user_id: current_user.id).order(created_at: :desc).pluck(:spot_id)
      @favorites = Spot.find(favorites)
    end
  end

  def update
    @user.update(user_params)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def authorize_user
    authorize @user = current_user
  end

  def user_params
    params.require(:user).permit(:spot_id)
  end
end

app/views/users/_form.html.erb
<%= simple_form_for [video, @comment] do |f| %>
  <div id="add-a-comment">
    <%= f.input :comment %>
    <div class='d-flex justify-content-between add-a-comment'>
      <%= link_to "Back", spot_path(params[:id]), class: 'btn btn-danger mr-3' %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_modal.html.erb
<!-- Button trigger modal -->
<div class="text-center mt-2" data-toggle="modal" data-target="#comment-<%= video.id %>">
   <i class="fas fa-comment-medical modal-comment"></i>
</div>
<!-- Modal -->
<div class="modal fade p-2" id="comment-<%= video.id %>" tabindex="-1" aria-labelledby="commentLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title modal-titles" id="commentLabel">Pleave leave a comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body rounded p-3">
        <%= render 'users/form', video: video %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3 text-center">
  <div class="card-profile">
    <%= cl_image_tag @user.photo.attached? ? cl_image_path(@user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-large" %>
    <h1 class="mt-3"><%= "#{@user.username}" %></h1>
  </div>
  <br>
  <div class="container mb-3">
    <% if @user.videos.present? %>
      <h1>Videos</h1>
      <% @user.videos.each do |video| %>
        <div class="card-video mb-5">
          <%= cl_video_tag(video.video.key, controls: true, width: 300, class: "card-img-top") %>
          <div class="video-infos" id="video-<%= video.id %>">
            <div>
              <p class="mr-5"><i class="fas fa-quote-left"></i> <%= video.caption.capitalize %></p>
            </div>
            <div class="d-flex align-items-center justify-content-center">
              <p class="mr-2"><%= video.votes %></p>
              <p><i data-video-id="<%= video.id %>" class="fas fa-comments comment-list"></i></p>
            </div>
          </div>
        </div>
        <div class="comments" id="comments-<%= video.id %>" >
          <%= render 'comments/modal', video: video %>
          <% video.comments.each do |comment| %>
            <i class="fas fa-quote-left"></i>
            <p><em><%= comment.comment %></em></p>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="container">
        <h2><%= "#{@user.username} hasn't uploaded any videos yet!" %></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/users/update.js.erb
document.getElementById("checked_in").innerHTML = "<%= escape_javascript render(partial: 'spots/checked_in', locals: {spot: @user.spot}) %>"
console.log("ok")