config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spots, only: [:index, :show, :new, :create] do
    resources :videos, only: [:new, :create]
    resources :reviews, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :update] do
    member do
      get :profile
    end
  end

  namespace :dashboard do
    resources :videos, only: [:index]
  end

  resources :videos, only: [:update] do
    resources :comments, only: [:create]
  end

  get '/videos/:id/upvote', to: 'videos#upvote', as: 'upvote'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar flex-nowrap navbar-expand-sm navbar-light">
  <% if current_user.present? %>
    <div class="dropdown">
      <button class="dropbtn">
        <%= cl_image_tag current_user.photo.attached? ? cl_image_path(current_user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered ml-2" %>
      </button>
      <div id="myDropdown" class="dropdown-content">
        <%= link_to "My Profile", dashboard_videos_path %>
        <%= link_to "Edit Profile", edit_user_registration_path %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </div>
    </div>
    <div class="container justify-content-end mr-2">
      <p style="word-spacing: 4px"><%= link_to "New Spot", new_spot_path %></p>
      <%= link_to new_spot_path do %>
        <p><i class="fas fa-plus ml-2 mr-4"></i></p>
      <% end %>
      <%= link_to spots_path do %>
        <p><i class="fas fa-map-marked-alt"></i></p>
      <% end %>
    </div>
  <% else %>
    <div class="container d-flex mb-2">
      <span class="mr-auto p-2"><%= link_to image_tag("sk8it-logo.png"), spots_path %></span>
      <span class="p-2"><%= link_to "Log In", new_user_session_path, class: "btn btn-gradient navbar-login" %></span>
      <span class="p-2"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-gradient navbar-signup" %></span>
    <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-bar pt-3">
  <%= form_tag spots_path, method: :get do %>
    <div class= "d-flex">
      <%= text_field_tag :query,
        params[:query],
        placeholder: "Find a spot"
      %>
      <%= button_tag type: 'submit', class: "search-bar" do %>
        <span><i class="fas fa-search"></i></span>
      <% end %>
    </div>
    <div class="radios mt-1">
      <div class="d-flex">
        <p><%= radio_button_tag(:spot, "spot") %></p>
        <p><%= label_tag(:spot_park, "Spots") %></p>
      </div>
      <div class="d-flex">
        <p><%= radio_button_tag(:shop, "shop") %></p>
        <p><%= label_tag(:spot_shop, "Shops") %></p>
      </div>
    </div>
  <% end %>
</div>